In [2]:
import pandas as pd

In [5]:
df = pd.read_excel(r"C:\Users\Khushboo Sharma\Desktop\US Staffing Project\US_IT_Staffing_Analytics_Dataset.xlsx") #read data

In [6]:
df #Look at the date

,Candidate ID,Candidate Name,Prime Vendor,End Client,BDM Name,Recruiter,Job Category,Job Type (C2C/W2/1099),Bill Rate,Pay Rate,Margin,Submission Date,Interview Date,Offer Date,Joining Date,Candidate Status
0,CAND1000,Elijah Davis,TEKsystems,JPMorgan Chase,Ankit Verma,Karan,Data Analyst,C2C,91,67,24,2025-01-02,2025-01-07,2025-01-08,NaN,Offer Released
1,CAND1001,William Williams,TEKsystems,AT&T,Rahul Mehta,Karan,DevOps Engineer,1099,94,64,30,2025-04-09,2025-04-14,2025-04-18,2025-05-02,Joined
2,CAND1002,Noah Moore,Randstad,AT&T,Neha Kapoor,Vikas,Java Developer,C2C,106,63,43,2025-02-08,2025-02-13,NaN,NaN,Rejected
3,CAND1003,Daniel Moore,Insight Global,Apple,Priya Singh,Ritika,Business Analyst,1099,118,66,52,2025-02-14,NaN,NaN,NaN,Submitted
4,CAND1004,Lucas Anderson,NTT DATA,Apple,Priya Singh,Karan,Data Analyst,1099,103,78,25,2025-05-02,2025-05-11,2025-05-14,2025-05-29,Joined
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,CAND1095,Elijah Johnson,Apex Systems,Apple,Neha Kapoor,Karan,DevOps Engineer,1099,80,59,21,2025-06-05,2025-06-10,2025-06-13,2025-06-29,Joined
96,CAND1096,Mia Brown,Kforce,Cisco,Ankit Verma,Pooja,Python Developer,1099,80,62,18,2025-01-21,NaN,NaN,NaN,Submitted
97,CAND1097,Emma Taylor,Experis,Apple,Ankit Verma,Deepak,Business Analyst,1099,98,68,30,2025-05-02,2025-05-08,2025-05-10,NaN,Offer Declined
98,CAND1098,Olivia Moore,TEKsystems,Amazon,Khushboo Sharma,Rohit,Data Engineer,1099,86,50,36,2025-04-14,2025-04-20,2025-04-25,2025-05-10,Joined
99,CAND1099,Isabella Johnson,Apex Systems,UnitedHealth Group,Ankit Verma,Rohit,Java Developer,W2,117,92,25,2025-03-05,2025-03-10,2025-03-11,NaN,Offer Released

In [7]:
df.head() # looking top 5 rows from data

,Candidate ID,Candidate Name,Prime Vendor,End Client,BDM Name,Recruiter,Job Category,Job Type (C2C/W2/1099),Bill Rate,Pay Rate,Margin,Submission Date,Interview Date,Offer Date,Joining Date,Candidate Status
0,CAND1000,Elijah Davis,TEKsystems,JPMorgan Chase,Ankit Verma,Karan,Data Analyst,C2C,91,67,24,2025-01-02,2025-01-07,2025-01-08,NaN,Offer Released
1,CAND1001,William Williams,TEKsystems,AT&T,Rahul Mehta,Karan,DevOps Engineer,1099,94,64,30,2025-04-09,2025-04-14,2025-04-18,2025-05-02,Joined
2,CAND1002,Noah Moore,Randstad,AT&T,Neha Kapoor,Vikas,Java Developer,C2C,106,63,43,2025-02-08,2025-02-13,NaN,NaN,Rejected
3,CAND1003,Daniel Moore,Insight Global,Apple,Priya Singh,Ritika,Business Analyst,1099,118,66,52,2025-02-14,NaN,NaN,NaN,Submitted
4,CAND1004,Lucas Anderson,NTT DATA,Apple,Priya Singh,Karan,Data Analyst,1099,103,78,25,2025-05-02,2025-05-11,2025-05-14,2025-05-29,Joined

In [8]:
df.tail()  #late 5 rows

,Candidate ID,Candidate Name,Prime Vendor,End Client,BDM Name,Recruiter,Job Category,Job Type (C2C/W2/1099),Bill Rate,Pay Rate,Margin,Submission Date,Interview Date,Offer Date,Joining Date,Candidate Status
95,CAND1095,Elijah Johnson,Apex Systems,Apple,Neha Kapoor,Karan,DevOps Engineer,1099,80,59,21,2025-06-05,2025-06-10,2025-06-13,2025-06-29,Joined
96,CAND1096,Mia Brown,Kforce,Cisco,Ankit Verma,Pooja,Python Developer,1099,80,62,18,2025-01-21,NaN,NaN,NaN,Submitted
97,CAND1097,Emma Taylor,Experis,Apple,Ankit Verma,Deepak,Business Analyst,1099,98,68,30,2025-05-02,2025-05-08,2025-05-10,NaN,Offer Declined
98,CAND1098,Olivia Moore,TEKsystems,Amazon,Khushboo Sharma,Rohit,Data Engineer,1099,86,50,36,2025-04-14,2025-04-20,2025-04-25,2025-05-10,Joined
99,CAND1099,Isabella Johnson,Apex Systems,UnitedHealth Group,Ankit Verma,Rohit,Java Developer,W2,117,92,25,2025-03-05,2025-03-10,2025-03-11,NaN,Offer Released

In [9]:
df.describe() # Summary statistics

        Bill Rate    Pay Rate      Margin
count  100.000000  100.000000  100.000000
mean    95.920000   66.760000   29.160000
std     14.665758   15.339999   14.514166
min     70.000000   45.000000   10.000000
25%     83.000000   56.750000   17.750000
50%     95.500000   63.000000   25.000000
75%    110.000000   78.000000   39.000000
max    120.000000  102.000000   70.000000

In [11]:
df.shape # total num of rows and col

(100, 16)

In [19]:
df.isnull().sum() #check the null values

Candidate ID              0
Candidate Name            0
Prime Vendor              0
End Client                0
BDM Name                  0
Recruiter                 0
Job Category              0
Job Type (C2C/W2/1099)    0
Bill Rate                 0
Pay Rate                  0
Margin                    0
Submission Date           0
Interview Date            0
Offer Date                0
Joining Date              0
Candidate Status          0
dtype: int64

In [16]:
# Handle missing values

df["Interview Date"] = df["Interview Date"] = fillna("No Interview")

In [17]:
df["Offer Date"] = df["Offer Date"].fillna("Coming Soon")

In [18]:
df["Joining Date"] = df["Joining Date"].fillna("pending")

In [20]:
df.isnull().sum()

Candidate ID              0
Candidate Name            0
Prime Vendor              0
End Client                0
BDM Name                  0
Recruiter                 0
Job Category              0
Job Type (C2C/W2/1099)    0
Bill Rate                 0
Pay Rate                  0
Margin                    0
Submission Date           0
Interview Date            0
Offer Date                0
Joining Date              0
Candidate Status          0
dtype: int64

In [22]:
df.duplicated().sum() #checking any duplicate values

np.int64(0)

In [37]:
#Clean column names

df.columns

Index(['CandidateID', 'CandidateName', 'PrimeVendor', 'EndClient', 'BDMName',
       'Recruiter', 'JobCategory', 'JobType', 'BillRate', 'PayRate', 'Margin',
       'SubmissionDate', 'InterviewDate', 'OfferDate', 'JoiningDate',
       'CandidateStatus'],
      dtype='object')

In [38]:
df.columns = df.columns.str.strip()

In [39]:
df.columns

Index(['CandidateID', 'CandidateName', 'PrimeVendor', 'EndClient', 'BDMName',
       'Recruiter', 'JobCategory', 'JobType', 'BillRate', 'PayRate', 'Margin',
       'SubmissionDate', 'InterviewDate', 'OfferDate', 'JoiningDate',
       'CandidateStatus'],
      dtype='object')

In [40]:
df.columns = df.columns.str.replace("_","")

In [32]:
df.columns

Index(['CandidateID', 'CandidateName', 'PrimeVendor', 'EndClient', 'BDMName',
       'Recruiter', 'JobCategory', 'JobType(C2C/W2/1099)', 'BillRate',
       'PayRate', 'Margin', 'SubmissionDate', 'InterviewDate', 'OfferDate',
       'JoiningDate', 'CandidateStatus'],
      dtype='object')

In [49]:
df.columns = df.columns.str.replace("JobType(C2C/W2/1099)","Job_Type")

In [42]:
df.columns

Index(['CandidateID', 'CandidateName', 'PrimeVendor', 'EndClient', 'BDMName',
       'Recruiter', 'JobCategory', 'JobType', 'BillRate', 'PayRate', 'Margin',
       'SubmissionDate', 'InterviewDate', 'OfferDate', 'JoiningDate',
       'CandidateStatus'],
      dtype='object')

In [44]:
df.columns

Index(['CandidateID', 'CandidateName', 'PrimeVendor', 'EndClient', 'BDMName',
       'Recruiter', 'JobCategory', 'JobType', 'BillRate', 'PayRate', 'Margin',
       'SubmissionDate', 'InterviewDate', 'OfferDate', 'JoiningDate',
       'CandidateStatus'],
      dtype='object')

In [48]:
df.columns = df.columns.str.lower()
df.columns

Index(['candidateid', 'candidatename', 'primevendor', 'endclient', 'bdmname',
       'recruiter', 'jobcategory', 'jobtype', 'billrate', 'payrate', 'margin',
       'submissiondate', 'interviewdate', 'offerdate', 'joiningdate',
       'candidatestatus'],
      dtype='object')

In [50]:
df.columns

Index(['candidateid', 'candidatename', 'primevendor', 'endclient', 'bdmname',
       'recruiter', 'jobcategory', 'jobtype', 'billrate', 'payrate', 'margin',
       'submissiondate', 'interviewdate', 'offerdate', 'joiningdate',
       'candidatestatus'],
      dtype='object')

In [52]:
df.columns = [
    "candidate_id",
    "candidate_name",
    "prime_vendor",
    "end_client",
    "bdm_name",
    "recruiter",
    "job_category",
    "job_type",
    "bill_rate",
    "pay_rate",
    "margin",
    "submission_date",
    "interview_date",
    "offer_date",
    "joining_date",
    "candidate_status"
]

In [53]:
df.columns

Index(['candidate_id', 'candidate_name', 'prime_vendor', 'end_client',
       'bdm_name', 'recruiter', 'job_category', 'job_type', 'bill_rate',
       'pay_rate', 'margin', 'submission_date', 'interview_date', 'offer_date',
       'joining_date', 'candidate_status'],
      dtype='object')

In [54]:
df.info() #df.dtypes both will show the datatypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   candidate_id      100 non-null    object
 1   candidate_name    100 non-null    object
 2   prime_vendor      100 non-null    object
 3   end_client        100 non-null    object
 4   bdm_name          100 non-null    object
 5   recruiter         100 non-null    object
 6   job_category      100 non-null    object
 7   job_type          100 non-null    object
 8   bill_rate         100 non-null    int64
 9   pay_rate          100 non-null    int64
 10  margin            100 non-null    int64
 11  submission_date   100 non-null    object
 12  interview_date    100 non-null    object
 13  offer_date        100 non-null    object
 14  joining_date      100 non-null    object
 15  candidate_status  100 non-null    object
dtypes: int64(3), object(13)
memory usage: 12.6+ KB

In [55]:
df.dtypes  #object means text

candidate_id        object
candidate_name      object
prime_vendor        object
end_client          object
bdm_name            object
recruiter           object
job_category        object
job_type            object
bill_rate            int64
pay_rate             int64
margin               int64
submission_date     object
interview_date      object
offer_date          object
joining_date        object
candidate_status    object
dtype: object

In [56]:
df["submission_date"] = pd.to_datetime(df["submission_date"])

In [59]:
df.dtypes

candidate_id                object
candidate_name              object
prime_vendor                object
end_client                  object
bdm_name                    object
recruiter                   object
job_category                object
job_type                    object
bill_rate                    int64
pay_rate                     int64
margin                       int64
submission_date     datetime64[ns]
interview_date              object
offer_date                  object
joining_date                object
candidate_status            object
dtype: object

In [60]:
df["bill_rate"] = df["bill_rate"].astype(float)

In [65]:
df["pay_rate"] = df["pay_rate"].astype(float)

In [64]:
df["margin"] = df["margin"].astype(float)

In [63]:
df.dtypes

candidate_id                object
candidate_name              object
prime_vendor                object
end_client                  object
bdm_name                    object
recruiter                   object
job_category                object
job_type                    object
bill_rate                  float64
pay_rate                   float64
margin                     float64
submission_date     datetime64[ns]
interview_date              object
offer_date                  object
joining_date                object
candidate_status            object
dtype: object

In [66]:
df["candidate_status"].unique()  #checking the unique values

array(['Offer Released', 'Joined', 'Rejected', 'Submitted',
       'Interview Scheduled', 'Offer Declined'], dtype=object)

In [67]:
df["candidate_status"] = df["candidate_status"].str.title()

In [68]:
df.info("candidate_status")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   candidate_id      100 non-null    object
 1   candidate_name    100 non-null    object
 2   prime_vendor      100 non-null    object
 3   end_client        100 non-null    object
 4   bdm_name          100 non-null    object
 5   recruiter         100 non-null    object
 6   job_category      100 non-null    object
 7   job_type          100 non-null    object
 8   bill_rate         100 non-null    float64
 9   pay_rate          100 non-null    float64
 10  margin            100 non-null    float64
 11  submission_date   100 non-null    datetime64[ns]
 12  interview_date    100 non-null    object
 13  offer_date        100 non-null    object
 14  joining_date      100 non-null    object
 15  candidate_status  100 non-null    object
dtypes: datetime64[ns](1), float64(3), object(12)
memory usage: 12.6+ KB

In [69]:
#Check Date Logic - it means I am checking that candidates joining date is later than the interview date 


df[df["joining_date"] < df["interview_date"]]

Empty DataFrame
Columns: [candidate_id, candidate_name, prime_vendor, end_client, bdm_name, recruiter, job_category, job_type, bill_rate, pay_rate, margin, submission_date, interview_date, offer_date, joining_date, candidate_status]
Index: []

In [71]:
#checking outliners in bill rate, pay rate and margin

df["bill_rate"].describe()

count    100.000000
mean      95.920000
std       14.665758
min       70.000000
25%       83.000000
50%       95.500000
75%      110.000000
max      120.000000
Name: bill_rate, dtype: float64

In [72]:
df["pay_rate"].describe()

count    100.000000
mean      66.760000
std       15.339999
min       45.000000
25%       56.750000
50%       63.000000
75%       78.000000
max      102.000000
Name: pay_rate, dtype: float64

In [73]:
df["margin"].describe()

count    100.000000
mean      29.160000
std       14.514166
min       10.000000
25%       17.750000
50%       25.000000
75%       39.000000
max       70.000000
Name: margin, dtype: float64

In [75]:
df[df["pay_rate"] > df["bill_rate"]]

Empty DataFrame
Columns: [candidate_id, candidate_name, prime_vendor, end_client, bdm_name, recruiter, job_category, job_type, bill_rate, pay_rate, margin, submission_date, interview_date, offer_date, joining_date, candidate_status]
Index: []

In [76]:
df[df["bill_rate"] < 0]

Empty DataFrame
Columns: [candidate_id, candidate_name, prime_vendor, end_client, bdm_name, recruiter, job_category, job_type, bill_rate, pay_rate, margin, submission_date, interview_date, offer_date, joining_date, candidate_status]
Index: []

In [77]:
df[df["pay_rate"] < 0]

Empty DataFrame
Columns: [candidate_id, candidate_name, prime_vendor, end_client, bdm_name, recruiter, job_category, job_type, bill_rate, pay_rate, margin, submission_date, interview_date, offer_date, joining_date, candidate_status]
Index: []

In [78]:
df[df["margin"] < 0]

Empty DataFrame
Columns: [candidate_id, candidate_name, prime_vendor, end_client, bdm_name, recruiter, job_category, job_type, bill_rate, pay_rate, margin, submission_date, interview_date, offer_date, joining_date, candidate_status]
Index: []

In [80]:
#Pandas does NOT automatically save your changes to the Excel file.
#saving the cleaned dataset coz the changes are made only in memory (inside Python session).

df.to_excel(
    r"C:\Users\Khushboo Sharma\Desktop\US Staffing Project\US_IT_Staffing_Cleaned.xlsx",
    index=False)

In [3]:
df= pd.read_excel(r"C:\Users\Khushboo Sharma\Desktop\US Staffing Project\US_IT_Staffing_Cleaned.xlsx")

In [4]:
df.head()

,candidate_id,candidate_name,prime_vendor,end_client,bdm_name,recruiter,job_category,job_type,bill_rate,pay_rate,margin,submission_date,interview_date,offer_date,joining_date,candidate_status
0,CAND1000,Elijah Davis,TEKsystems,JPMorgan Chase,Ankit Verma,Karan,Data Analyst,C2C,91,67,24,2025-01-02,2025-01-07,2025-01-08,pending,Offer Released
1,CAND1001,William Williams,TEKsystems,AT&T,Rahul Mehta,Karan,DevOps Engineer,1099,94,64,30,2025-04-09,2025-04-14,2025-04-18,2025-05-02,Joined
2,CAND1002,Noah Moore,Randstad,AT&T,Neha Kapoor,Vikas,Java Developer,C2C,106,63,43,2025-02-08,2025-02-13,Coming Soon,pending,Rejected
3,CAND1003,Daniel Moore,Insight Global,Apple,Priya Singh,Ritika,Business Analyst,1099,118,66,52,2025-02-14,No Interview,Coming Soon,pending,Submitted
4,CAND1004,Lucas Anderson,NTT DATA,Apple,Priya Singh,Karan,Data Analyst,1099,103,78,25,2025-05-02,2025-05-11,2025-05-14,2025-05-29,Joined

In [6]:
#Connecting with SQL 

!pip install SQLALchemy pymysql

Requirement already satisfied: SQLALchemy in c:\users\khushboo sharma\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\users\khushboo sharma\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: greenlet>=1 in c:\users\khushboo sharma\anaconda3\lib\site-packages (from SQLALchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\khushboo sharma\anaconda3\lib\site-packages (from SQLALchemy) (4.15.0)

In [7]:
from sqlalchemy import create_engine 

connection = create_engine("mysql+pymysql://root:7321@localhost/us_staffing")

In [10]:
df.to_sql(
    name = "staffing_data", #we are creating a table(not already in mysql)
    con = connection,   #using the connection - this will connect to the database(already in sql)
    if_exists="replace",    # Replace table if it already exists
    index=False             # Don't create an extra index column
)
print("Data successfully uploaded to MySQL!")

Data successfully uploaded to MySQL!